import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { inter, FiraCode, orbitron, jakarta, roboto } from "@/config/font";

import TestElement from "@/components/textElements/test";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`   ${inter.variable} ${FiraCode.variable} ${orbitron.variable} ${jakarta.variable} ${roboto.variable}`}
				>
					{/* <TestElement /> */}
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
